### ISSUE TITLE
docker exporter and grafana dashboard

### ISSUE THREAD

**Issue by acaranta** [brmurphy/eero-exporter#1]
Hey !

Not really an issue, more or notification.

I created a docker wrapper to run your code (it actually pull you repo on build :) ) more easily code can be found at  https://github.com/acaranta/docker-eero-prometheus-exporter Docker image is built on the hub at https://hub.docker.com/repository/docker/acaranta/eero-exporter 
and also created a basic Grafana Dashboard for the metrics, available here  https://grafana.com/grafana/dashboards/13558

Thanks for your work :)

**Comment by brmurphy** [comment]
That's great, thank you @acaranta !

**Comment by brmurphy** [comment]
@acaranta you inspired me to upload my own dashboard too

https://grafana.com/grafana/dashboards/13842
